version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - 'yarn --ignore-engines'
      - 'touch .npmignore'
      - 'npm install -g gatsby'
pre_build:
  commands:
    - 'npm ci --production'
build:
  commands:
    - 'npm run-script clean && build'
post_build:
  commands:
    - 'npm run-script deploy'
artifacts:
  base-directory: public
  files:
    - build*/**
discard-paths: yes
cache:
  paths:
    - '.cache/*'
    - 'public/*'