version: 0.2
phases:
 install:
  runtime-versions:
    nodejs: 10
  commands:
    - echo "install step"
    - npm install -g gatsby
 pre_build:
  commands:
    - echo "pre_build step"
    - npm install
 build:
  commands:
    - npm run build
 post_build:
  commands:
    - aws s3 sync --delete "./public/" "s3://testing-gatsbyjs" --acl "public-read"
    - echo "post_build step"